#!/usr/bin/php
<?php
function pushstream( $channel, $data ) {
	$ch = curl_init( 'http://localhost/pub?id='.$channel );
	curl_setopt( $ch, CURLOPT_HTTPHEADER, array( 'Content-Type:application/json' ) );
	curl_setopt( $ch, CURLOPT_POSTFIELDS, json_encode( $data, JSON_NUMERIC_CHECK ) );
	curl_exec( $ch );
	curl_close( $ch );
}

$redis = new Redis();
$redis->pconnect( '127.0.0.1' );
if ( $argv[ 1 ] === 'off' ) {
	pushstream( 'airplay', 0 );
	exec( '/usr/bin/sudo /usr/bin/systemctl start mpd; /usr/bin/killall enhanceshairport &> /dev/null &' );
	$redis->set( 'activePlayer', 'MPD' );
	exit();
}

// set output_device
exec( '/usr/bin/sudo /usr/bin/systemctl stop mpd' );
$redis->set( 'activePlayer', 'Airplay' );

/* stdout stream from /tmp/shairport-sync-metadata fifo/named pipe:
...
<item><type>636f7265</type><code>6173616c</code><length>18</length>
<data encoding="base64">
U29uZ3Mgb2YgSW5ub2NlbmNl</data></item>
...
*/

$metadata = fopen( '/tmp/shairport-sync-metadata', 'r' );
$code = '';
while ( 1 ) {
	$lines = fgets( $metadata );
	$line = strtok( $lines, "\n" ); //////////
	
	while ( $line ) {
		if ( strpos( $line, '61736172' ) ) {
			$code = 'Artist';
		} else if ( strpos( $line, '6d696e6d' ) ) {
			$code = 'Title';
		} else if ( strpos( $line, '6173616c' ) ) {
			$code = 'Album';
		} else if ( strpos( $line, '50494354' ) ) {
			$code = 'coverart';
		}
		if ( $code && strpos( $line, '</data></item>' ) ) {
			$data = str_replace( '</data></item>', '', $line );
			if ( $code === 'coverart' ) {
				$coverart = 'data:image/jpeg;base64,'.$data; // airplay - only jpeg
				file_put_contents( '/srv/http/assets/img/airplaycoverart', $coverart );
			} else {
				$redis->hSet( 'airplaymeta', $code, base64_decode( $data ) );
				pushstream( 'airplay', 1 );
			}
			$code = '';
		}
		
		$line = strtok( "\n" ); //////////
	}
}
fclose( $metadata );
