#!/usr/bin/php
<?php
$redis = new Redis();
$redis->pconnect( '127.0.0.1' );

if ( $argv[ 1 ] === 'off' ) {
	exec( '/usr/bin/sudo /usr/bin/systemctl start mpd' );
	$redis->set( 'activePlayer', 'MPD' );
	exit();
}

exec( '/usr/bin/sudo /usr/bin/systemctl stop mpd' );
$redis->set( 'activePlayer', 'Airplay' );

/* stdout stream from /tmp/shairport-sync-metadata fifo/named pipe:
...
<item><type>636f7265</type><code>6173616c</code><length>18</length>
<data encoding="base64">
U29uZ3Mgb2YgSW5ub2NlbmNl</data></item>
...
*/
$replace = array(
	  '#<item><type>.*</type><code>.*</code><length>0</length>.*\\n#' => ''      // remove zero length
	, '#<item><type>.*</type><code>(.*)</code><length>.*</length>.*\\n#' => "$1" // get 'code'
	, '#<data encoding="base64">\\n#' => ''                                      // remove encoding="base64" line
	, '#(.*)</data></item>.*\\n#' => "$1"                                        // get 'data'
	, '#.*</item>.*\\n#' => ''                                                   // remove trailling '</item>'
);
$airplay_handle = fopen( '/tmp/shairport-sync-metadata', 'r' );
stream_set_blocking( $airplay_handle, false );
$i = 0;
while ( 1 ) {
	$line = fgets( $airplay_handle );
	$std = preg_replace( array_keys( $replace ), array_values( $replace ), $line );
	if ( !$std ) continue;

	if ( $i === 0 ) {
		$i = 1;
		$code = hex2bin( $std );
		echo $code;
	} else {
		$i = 0;
		$data = base64_decode( $std );
		echo $data;
		$status[ 'cover' ] = '';
		
		if ( $code === 'asar' ) {
			$status[ 'currentartist' ] = $data;
		} else if ( $code === 'minm' ) {
			$status[ 'currentsong' ] = $data;
		} else if ( $code === 'asal' ) {
			$status[ 'currentalbum' ] = $data;
		} else if ( $code === 'PICT' ) {
			exec( '/usr/bin/rm -f /srv/http/assets/img/airplay.*.jpg' );
			$status[ 'cover' ] = '/srv/http/assets/img/airplay.'.time().'.jpg';
			$fopen = fopen( $status[ 'cover' ], 'wb' );
			fwrite( $fopen, $data );
			fclose( $fopen );
		} else if ( $code === 'prgr' ) { // each send end with 'prgr'
			$progress = explode( '/', $data );
			$status[ 'elapsed' ] = round( ( $progress[ 0 ] - $progress[ 1 ] ) / 44100 );
			$status[ 'time' ] = round( ( $progress[ 2 ] - $progress[ 1 ] ) / 44100 );
			// airplay broadcasts status on track changed only
			$redis->set( 'act_player_info', json_encode( $status ) );
		}
	}
}
