#!/bin/bash

export XDG_CACHE_HOME="/tmp/.cache" &
export DISPLAY=":0" &

xset dpms 0 0 0 &
xset s off &
xset -dpms &

# keyboard shortcuts
#xbindkeys -X ":0" &

exec chromium --app=http://localhost --kiosk --start-fullscreen --disable-gpu --force-device-scale-factor=1.8
