#!/bin/bash

if (( $# > 1 )); then
	enabled=$( mpc outputs | grep enabled | head -1 | awk -F'[()]' '{print $2}' )
	redis-cli set ao "$enabled"
	aplay=$( aplay -l | grep card | tail -1 ) # last line = new power-on card
	sysname=$( echo $aplay | awk -F'[][]' '{print $2}' )
	name=$( grep extlabel "/src/http/settings/acards/dac/$sysname" | cut -d: -f2- )
	/src/http/settings/acards/acards_mpdconf.sh
else
	name=$( redis-cli get ao )
fi

mpc enable only "$name"

curl -s -X POST 'http://localhost/pub?id=notify' -d '{ "title": "Audio Output Switched", "text": "'"$name"'", "icon": "output" }'
